Repository CMPUT301F23T21/EZVault, pull requests merged in 2023-11, with the labels that each got.

#47 Add value and quantity to item
  app/src/main/java/com/example/ezvault/database/ItemDAO.java
  app/src/main/java/com/example/ezvault/model/Item.java
  app/src/main/java/com/example/ezvault/model/ItemBuilder.java
Labels: enhancement

#48 Make ItemList implement List<Item>
  app/src/main/java/com/example/ezvault/model/ItemList.java
Labels: enhancement

#34 Adds UML Class Diagram (Plant UML)
  app/src/main/java/com/example/ezvault/WelcomeFragment.java
  app/src/main/java/com/example/ezvault/authentication/registration/FirebaseRegistrationStrategy.java
  app/src/main/res/layout/add_item.xml
  doc/puml/.gitignore
  doc/puml/authentication/authentication.puml
  doc/puml/authentication/registration.puml
  doc/puml/classDiagram.svg
  doc/puml/database.puml
  doc/puml/frag.puml
  doc/puml/main.puml
  doc/puml/model.puml
  doc/puml/utils.puml
Labels: documentation

#62 Gallery rework
  app/src/main/java/com/example/ezvault/camera/CameraAction.java
  app/src/main/java/com/example/ezvault/camera/GalleryAction.java
  app/src/main/java/com/example/ezvault/model/ActivityTaskChunk.java
Labels: bug, enhancement

#63 Item Filtering - Backend
  app/build.gradle.kts
  app/src/main/java/com/example/ezvault/ItemAdapter.java
  app/src/main/java/com/example/ezvault/ItemsFragment.java
  app/src/main/java/com/example/ezvault/model/Item.java
  app/src/main/java/com/example/ezvault/model/ItemList.java
  app/src/main/java/com/example/ezvault/model/utils/ItemListView.java
  app/src/main/java/com/example/ezvault/model/utils/filter/IItemFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemConjunctionFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemDateFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemKeywordFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemListFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemMakeFilter.java
  app/src/main/java/com/example/ezvault/model/utils/filter/ItemTagFilter.java
Labels: enhancement

#69 Adds Basic Tag Support
  app/src/main/java/com/example/ezvault/TagsFragment.java
  app/src/main/java/com/example/ezvault/database/UserService.java
  app/src/main/java/com/example/ezvault/view/TagDialogue.java
  app/src/main/java/com/example/ezvault/view/TagsFragment.java
  app/src/main/java/com/example/ezvault/view/adapter/TagRecyclerAdapter.java
  app/src/main/java/com/example/ezvault/viewmodel/TagsViewModel.java
  app/src/main/res/layout/fragment_tags.xml
  app/src/main/res/navigation/navgraph.xml
Labels: enhancement
